alias brew="env PATH=${PATH/\/Users\/tasukujp\/\.pyenv\/shims:/} brew"
alias brew="env PATH=${PATH/\/Users\/taka\/\.pyenv\/shims:/} brew"
alias brew="env PATH=${PATH/\/opt\/local\/\bin:/} brew"
alias brew="env PATH=${PATH/\/opt\/local\/\bin:/} brew"
alias brew="env PATH=${PATH/\/opt\/local\/\bin:/} brew"
